site_name: Guardium Notes Labs
site_description: Labs for TZ based Guardium Data Protection workshop

theme:
  name: material
  

  palette:
    scheme: slate
    primary: deep purple
    accent: amber
    
  palette:
    scheme: slate
    primary: deep purple
    accent: amber
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.follow
    - search.highlight
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.keys
  - md_in_html

extra_css:
- stylesheets/extra.css

nav:
  - Home: index.md
  - V14:
      - Access to Lab: v14/access.md
      - Appliance setup (lab 1): v14/appliance.md
      - GIM (lab 2): v14/gim.md
      - KTAP (lab 3): v14/ktap.md
  